apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv02
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/es-pv02
