apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv01
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 4Gi
    accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/pv0001/

