apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv02
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
    storageClassName: local-storage
    accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/pv0002/